VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes
QMK_SETTINGS = yes

#Features 
KEY_OVERRIDE_ENABLE = no
TAP_DANCE_ENABLE = no
VIAL_ENCODERS_ENABLE = no

#Disabled for space
BOOTMAGIC_ENABLE = no 
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no 
COMMAND_ENABLE = no 
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no 
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no
UNICODE_ENABLE = no
UNICODEMAP_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no
COMBO_ENABLE = no
KEY_LOCK_ENABLE = no
AUTO_SHIFT_ENABLE = no
LEADER_ENABLE = no
MUSIC_ENABLE = no